import = [
	"~/.config/alacritty/keybindings.toml",
	"~/.config/alacritty/themes/mytheme.toml",
	"~/.config/alacritty/settings/window.toml",
	"~/.config/alacritty/settings/fonts.toml",
	"~/.config/alacritty/settings/colors.toml",
	"~/.config/alacritty/settings/cursor.toml",
	"~/.config/alacritty/settings/hints.toml",
]
